/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:af9398de-ca3c-46c8-825c-98ff67ec5e88",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Y9d2HBeqo",
    "aws_user_pools_web_client_id": "27qvjtp9pumgv5fvtn8do404d6",
    "oauth": {}
};


export default awsmobile;
